### ISSUE TITLE
Info: domain change

### ISSUE THREAD

**Issue by mkalb** [MovingBlocks/legacy-website#28]
https://github.com/blog/1452-new-github-pages-domain-github-io

**Comment by Cervator** [comment]
Heh, nice timing, right after we got set up!

Good news is that our custom domain is unaffected by the change, and the rename of this repo to .io instead of .com is optional (and doesn't gain us anything)

Nothing currently forwards to movingblocks.github.com, which will get permanently redirected anyway, so that's good.

We should be alright - but thanks for catching that, I'm happy to have gone through the review process to be comfortable all is still well - closing :-)
