### ISSUE TITLE
Google Analytics & Ajax - closer integration?

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/legacy-website#30]
This is mainly a question for @MiJyn or somebody well-versed in Ajax and Google Analytics :-)

I added GA and can see statistics now (60 pageviews for Monday, wee!) but only have a single metric, which probably makes sense since there's only one URL / html file loaded and we swap page content around with Ajax magic.

I wonder if there's any way to capture better analytics to where we can see what menus users have navigated through? Do we just reload the analytics JS file inside the Ajax html snippet or something?

I'm extremely new to GA myself so I'm not sure what options are available and thought I'd ask :-)

**Comment by AnonymousMeerkat** [comment]
Hmm... I have no idea if this would work, buuuut.... maybe if we used the hashtag at the end of the URL (you know, index.html#about), maybe google analytics could record that....

Probably not, on second thought (keeping the idea though, just in case), since google analytics would (probably) need to re-load... so maybe if we removed the google analytics script tag, and added a new one to re-load it?

Sounds awfully hacky though, and I'm not sure if this is good or not... Maybe we could reverse-engineer it to figure out how to do it? But then, if it changes, we'll be stuck with a non-working site

In any case, I think we'll still use the first idea, so that you can know which pages were accessed.

**Comment by Cervator** [comment]
I have no real clue :D If something seems doable, feel free to try, if not then that's hardly the end of the world :-)

**Comment by Cervator** [comment]
Not convinced this is really worth any serious effort - if some easy way to do it pops up cool, but if not we can live without. So closing this for now :-)
