### ISSUE TITLE
Extended Google preview entry prep

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/legacy-website#42]
Fancy sites have a few extended links listed under their entry on Google. The splash site should be so fancy!
- Download
- Applet
- Forum
- Etc

Admittedly I'm not actually sure how that's done, but I _figure_ it is in the HTML somewhere so we can do it even fronted by GitHub :-)

**Comment by AnonymousMeerkat** [comment]
Yeah, we can't do that, sorry ... Google generates it automatically (we can, however, ask them to change it)

**Comment by Cervator** [comment]
Aw :-)

There isn't a way to add some meta-tags that encourages their parser to find stuff we want to display?

**Comment by nnsdev** [comment]
No that's wrong @MiJyn. It works, but I think we have to create that in Google. Have to search for it.

**Comment by neoascetic** [comment]
It is impossible at the current moment since these links are images, not a text. I am working on the solution.

**Comment by small-jeeper** [comment]
Опа. Земеля:)

**Comment by neoascetic** [comment]
@small-jeeper Земля квадратная, за углом встретимся :D

**Comment by small-jeeper** [comment]
@neoascetic Еще и с того же города что и я. Еще и веб разработчик как я:) Паш, зарегистрируйся на forum.movingblocks.net плз :)

**Comment by nnsdev** [comment]
I fixed that in my recode.
Actually I am thinking about why this page isn't HTML5 supported, this will also need some work, when I'm on my Computer I will try to fix some other things and update jquery etc.

**Comment by neoascetic** [comment]
@NowNewStart seems like we both do same work... I will send an PR in a hour.

**Comment by nnsdev** [comment]
Does this even work? We only have one file, and I don't know if we can make a sitemap that it calls the pages in that file.

**Comment by Cervator** [comment]
I don't know, the issue was pretty much meant as research into finding out that Google preview thing works and if it was suitable for our splash site. If the answer to that is "no", which might be especially likely now that it is effectively one page, then we can close this - no big deal :-)

**Comment by neoascetic** [comment]
@Cervator do you mean these links?
![screenshot 2014-02-15 10 23 01](https://f.cloud.github.com/assets/725836/2176272/f95ba444-95ce-11e3-90d7-892c305b12f2.png)

Or these?
![screenshot 2014-02-15 10 11 12](https://f.cloud.github.com/assets/725836/2176189/60932260-95cd-11e3-91f7-30681510f4fa.png)

Or any type of them?

---

If first, then google builds them automatically and this is probably impossible to create them on one-page website. For second type of sitelinks IMO this is possible because these links are simply build from unordered list element that exist on a requested page. I'll wrap all links in our index menu into unordered list and we can hope that google will understand what we want him by doing this.

**Comment by Cervator** [comment]
I hadn't even realized there were two different kinds :D But yeah either would've been fine if doable, and fine if not, thanks for giving it a try!
