### ISSUE TITLE
Create a template blog post for new launcher or game releases

### ISSUE THREAD

**Issue by smsunarto** [MovingBlocks/legacy-website#75]
Currently we only announce new release on our social media accounts and forums. We should also announce this on our website. A template blog post will make this announcement process easier.

- [ ] "New Release/Update" Banner (Art)
- [ ] Template with change log, informations, etc (Writing)

CC: @Cervator

**Comment by kenkirito** [comment]
can I work on this issue

**Comment by skaldarnar** [comment]
Hi @kenkirito,

I think this issue is a bit outdated by now :thinking: 

We are doing (more or less) regular TeraSaturday posts, following the same kind of structure each time. Templates for banner images for both blog posts and modules can be found in the [press kit (Google Drive)](https://drive.google.com/drive/folders/1Y5uO102QSAydUAoxSYtPerxVg6k6mCbI).

Sorry for the inconvenience here. We should go over the open issues and update them to reflect current tasks. I'll take this into our organization sync today :+1: 

In the meantime you could join our [Discord server](https://discord.com/invite/terasology) and say hi, we'll help you find a good starter task then :wink:

**Comment by kenkirito** [comment]
Np ☺✌
